### get ALL Items
GET http://localhost:8079/api/v1/items
Authorization: Basic vadim admin
Accept: application/json
###

### get item by ID
GET http://localhost:8079/api/v1/items/2
Authorization: Basic vadim admin
Accept: application/json

### delete item
DELETE http://localhost:8079/api/v1/items/2
Authorization: Basic vadim admin
Accept: application/json

### Create Item
POST http://localhost:8079/api/v1/items
Authorization: Basic vadim admin
Accept: application/json
Content-Type: application/json

{
  "id": "4",
  "name": "test4",
  "description": "dis4"
}


### Update Item
POST http://localhost:8079/api/v1/items
Authorization: Basic vadim admin
Accept: application/json
Content-Type: application/json

{
  "id": "2",
  "name": "updated name2",
  "description": "dis2"
}

### Get name by id
GET http://localhost:8079/api/v1/items/name/3
Authorization: Basic vadim admin
Accept: application/json

### Hello admin
GET http://localhost:8079/api/v1/items/helloadmin
Authorization: Basic vadim admin
Accept: application/json

### Hello user
GET http://localhost:8079/api/v1/items/hellouser
Authorization: Basic vadim admin
Accept: application/json

### Hello guest
GET http://localhost:8079/api/v1/items/helloguest
Authorization: Basic vadim admin
Accept: application/json
###
